name: API Testing Workflow
'on':
  - push
  - workflow_dispatch
jobs:
  test-runner:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        run: ["g4m", "av"]
    env:
      API_URL: 'https://pokeapi.co/api/v2'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm ci
      - name: Run ESLint
        run: npx eslint --quiet
      - name: Run tests and generate report
        env:
          TEST_REPORT_PATH: report.xml
        run: npm test -- --reporter=mocha-junit-reporter
      - name: Upload test report as artifact
        uses: actions/upload-artifact@v2
        with:
          name: Test Report From Runner
          path: ./test-results.xml
      - name: Set job report variables
        run: |
          echo "JOB_STATUS=${{ job.status }}" >> $GITHUB_ENV
          sed -i "s/\$JOB_STATUS/${{ job.status }}/g" ".github/slack-messaging/slack-payload.json"

          echo "URL=${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" >> $GITHUB_ENV
          sed -i "s/\$URL/${{ env.URL }}/g" ".github/slack-messaging/slack-payload.json"

          echo "MATRIX_RUN=${{ matrix.run }}" >> $GITHUB_ENV

      - name: Notify on Slack
        uses: slackapi/slack-github-action@v1.24.0
        with:
          channel-id: "C058GP7SQA0"
          payload-file-path: .github/slack-messaging/slack-payload-${{ env.MATRIX_RUN }}.json
        env:
          SLACK_BOT_TOKEN: ${{ secrets.WDIO_SLACKBOT_TOKEN }}