name: Daily API Tests
'on':
  - push
  - workflow_dispatch
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      API_URL: 'https://pokeapi.co/api/v2'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm ci
      - name: Run ESLint
        run: npx eslint --quiet
      - name: Run tests and generate report
        env:
          TEST_REPORT_PATH: report.xml
        run: |
          npm test -- --reporter=mocha-junit-reporter --reporter-options mochaFile=./test-results.xml
      - name: Upload test report as artifact
        uses: actions/upload-artifact@v2
        with:
          name: Test Report
          path: ./test-results.xml
      - name: Notify on Slack
        uses: slackapi/slack-github-action@v1.24.0
        with:
          channel: "C0588A9DJQN"
          status: ${{ job.status }}
          payload-file-path: ".github/slack-messaging/slack-payload.json"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK



  